version: '3.8'
services:
  backend:
    build: .
    ports:
      - "3000:3000"
    command: npm run dev:backend
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development 
      - PORT=3000
  frontend:
    build: .
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    command: npm run dev:frontend
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - backend