app = 'carlos-challenge'
primary_region = 'mad'

[build]
  dockerfile = 'Dockerfile'
  [build.args]
    VITE_API_URL="https://carlos-challenge.fly.dev"

[env]
  NODE_ENV = 'production'
  PORT = '3000'
[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
